language: ruby
rvm:
  - 2.3.7
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
gemfile:
  - Gemfile
before_script:
  - mysql -e 'create database strano_test'
  - psql -c 'create database strano_test' -U postgres
  - RAILS_ENV=test bundle exec rake app:db:migrate
  - bundle exec rake app:db:test:prepare
